### PR TITLE
Support multiple classes in className

### LINKED ISSUE #8: className does not support multiple classes
The error `InvalidCharacterError (DOM Exception 5): The string contains invalid characters.` happens [here](https://github.com/bbatliner/vex-dialog/blob/master/src/vex.dialog.js#L33).

Use case would be modifier classes (e.g. `btn btn--progress`).

This is a regression after updating from vex 2.

### PR DESCRIPTION
**Pull request by mlazowik**
Closes #8

### CODE REVIEW

**Comment by mlazowik** [comment]
This is using two APIs for the same thing next to each other, but I think that doing split and `add` on each is worse. And probably slower.

Another option is to change other instances of `classList` to `className`. Or just forget about it. What do you think?

**Comment by Luke-Niwranski** [comment]
I just quickly fixed the issue using the following:

`domButton.classList.add.apply(domButton.classList, button.className.split(" "))`

Allows existing 2.x code to work without modification.

**Comment by ghost** [comment]
* @Luke-Niwranski  could you make a new MR with your suggestion? 
* Or @mlazowik, would you like to change your MR to use what @Luke-Niwranski suggested?
* Or @bbatliner, could you just fix merge this suggestion?
* Or shall I create a new merge request?

Could we just fix this issue?

**Comment by mlazowik** [comment]
I still stand by my first comment, namely that `className` version is much more readable. Also faster, but I can't imagine any case where that would matter.

Now that I look at it appending is not even needed, an assignment would also work, as the element is created just before it.

Either way the problem is that it looks like this repo is abandoned.

**Comment by bbatliner** [comment]
Not abandoned...

@mlazowik I agree, appending is not needed and we can use the `className` version. I will merge this in and update on npm. I will also update the main [vex](https://github.com/HubSpot/vex) repo with the updated version of vex-dialog and hope to have an update published on npm soon.

**Comment by mlazowik** [comment]
Great, thanks!

**Pull request merged**
