### PR TITLE
Safe by default

### PR DESCRIPTION
**Pull request by bbatliner**
I created a new branch `safe-by-default` on vex2-dialog where we can track the status of merging @markstos's changes back into vex2-dialog.

### CODE REVIEW

**Comment by bbatliner** [comment]
I don't think merging the whole fork will be feasible. But I can probably cherry-pick things like the documentation changes and go from there.

Anyways, I put the safe by default functionality in df036c8. I'd appreciate it if you can give it a glance and see if it's how you intended it to be in your fork.

**Comment by bbatliner** [comment]
Do you think `vex2` should also be safe by default? It has a `content` option that will parse HTML by default.

**Comment by markstos** [comment]
> Do you think vex2 should also be safe by default? 

I haven't looked at what `vex` does apart from `dialog`, but these seem like a reasonable guidelines:
- If a function most commonly accepts a string as input, like `alert()`, then HTML-escaping should be enabled by default for the function-- treat the input as a string by default, not HTML.
- If a function most commonly accepts HTML as input, then HTML-sanitizing should be enabled by default. (ex: stripping out out <script> tags, JavaScript event handling attributes, and so on).

Or more generally: treat the input as strict as reasonably makes sense.

**Comment by markstos** [comment]
> I don't think merging the whole fork will be feasible. But I can probably cherry-pick things like the documentation changes and go from there.

Understood. Take what makes sense in the context of your current work.

**Comment by bbatliner** [comment]
I manually merged your [documentation changes](https://github.com/HubSpot/vex/pull/160/commits/f73d6a8c52f5f8cfadfe10b62259142e67cceb77) in to my vex fork. Thanks so much!

**Pull request closed without merging**
